iio: adc: talise-api: ignore ISO C90 vla warnings
On newer kernels warning/error is:
```
drivers/iio/adc/talise/talise_gpio.c:2032:5: error: ISO C90 forbids array 'gpioStatus' whose size can't be evaluated [-Werror=vla]
 2032 |     uint8_t gpioStatus[GPIO_STATUS_CMD_SIZE_BYTES];
```

It's probable that upstream kernel decided to enforce some C90 stuff [vs
C99]. We won't fix this code, but we will ignore it so that it builds on
the adi-iio branch.

Signed-off-by: Alexandru Ardelean <alexandru.ardelean@analog.com>
(cherry picked from commit 5591919cee8a8a965863510792b3cadc49ced9ce)